### ISSUE TITLE
[DS] Linked List in Python

### ISSUE THREAD

**Issue by skahk** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#27]
# Data Structure

- [x] I have gone through the repository and made sure this data structure has not been implemented

## Information about my new data structure

- **Data Structure: Linked List** 

- **Programming Language: Python** 

**Is this your first contribution to this repository?**
Yes

**Comment by Laronk** [comment]
On it!

**Comment by Laronk** [comment]
Done, see #31

**Comment by frextrite** [comment]
Hey @Laronk, please don't work on issues without being getting assigned on them :) @skahk was meant to work on this. However, since you have already created a PR, I'm going to review it this time but please take care next time.

@skahk I'm really sorry for this. You can work on some other DS/Algo (there're plenty left). Create an issue and drop a message, I'll assign it to you. 😃
